<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Lab_IPO1</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="datos\platos.xml" />
    <None Remove="imagenes\ajuste.png" />
    <None Remove="imagenes\arroz-con-leche.jpg" />
    <None Remove="imagenes\cerveza.jpg" />
    <None Remove="imagenes\cobrarIcon.png" />
    <None Remove="imagenes\cocacola.jpg" />
    <None Remove="imagenes\contrasenaIcono.png" />
    <None Remove="imagenes\CroquetasJamon.jpg" />
    <None Remove="imagenes\cross.png" />
    <None Remove="imagenes\dinero-en-efectivo.png" />
    <None Remove="imagenes\dinero.png" />
    <None Remove="imagenes\Ensalada-cesar-con-pasta-3.jpg" />
    <None Remove="imagenes\ensalada_mediterranea_de_atun_32697_orig.jpg" />
    <None Remove="imagenes\entrecot-a-la-plancha-poco-hecho-receta.jpg" />
    <None Remove="imagenes\escoba.png" />
    <None Remove="imagenes\espaguetis-a-la-carbonara-1.jpg" />
    <None Remove="imagenes\estofado.jpeg" />
    <None Remove="imagenes\helado-de-vainilla.jpg" />
    <None Remove="imagenes\help.png" />
    <None Remove="imagenes\iconoTPV.png" />
    <None Remove="imagenes\lasania.jpg" />
    <None Remove="imagenes\llamar.png" />
    <None Remove="imagenes\logo.png" />
    <None Remove="imagenes\logout.png" />
    <None Remove="imagenes\lupaIcono.png" />
    <None Remove="imagenes\menuCLientesOff.png" />
    <None Remove="imagenes\menuCLientesOff1.png" />
    <None Remove="imagenes\menuClientesOn.png" />
    <None Remove="imagenes\menuCLientesOn1.png" />
    <None Remove="imagenes\menuPedidosOff.png" />
    <None Remove="imagenes\menuPedidosOn.png" />
    <None Remove="imagenes\menuProductosOff.png" />
    <None Remove="imagenes\menuProductosOn.png" />
    <None Remove="imagenes\negocio-local.png" />
    <None Remove="imagenes\nuevoPedido.png" />
    <None Remove="imagenes\ojoOff.png" />
    <None Remove="imagenes\ojoOn.png" />
    <None Remove="imagenes\Paellavalenciana-4.jpg" />
    <None Remove="imagenes\pago-con-tarjetas-de-credito.png" />
    <None Remove="imagenes\pedidosOff.png" />
    <None Remove="imagenes\pedidosOn.png" />
    <None Remove="imagenes\pedidosOn1.png" />
    <None Remove="imagenes\perfil.png" />
    <None Remove="imagenes\productos.png" />
    <None Remove="imagenes\productosOff.png" />
    <None Remove="imagenes\productosOff1.png" />
    <None Remove="imagenes\productosOn.png" />
    <None Remove="imagenes\productosOn1.png" />
    <None Remove="imagenes\rioja-vega-crianza.png" />
    <None Remove="imagenes\salmon-horno-patatas-scaled.jpg" />
    <None Remove="imagenes\sopa-de-cebolla-receta.jpg" />
    <None Remove="imagenes\tarta-de-queso-de-la-vina.jpg" />
    <None Remove="imagenes\tick.png" />
    <None Remove="imagenes\usuarioIcono.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="datos\platos.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\ajuste.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\menuCLientesOff1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\menuCLientesOn1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\pedidosOff.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\pedidosOn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\pedidosOn1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\productosOff.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\productosOff1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\productosOn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\productosOn1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\usuarioIcono.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="imagenes\arroz-con-leche.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\cerveza.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\cobrarIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\cocacola.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\contrasenaIcono.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\CroquetasJamon.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\cross.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\Ensalada-cesar-con-pasta-3.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\espaguetis-a-la-carbonara-1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\ensalada_mediterranea_de_atun_32697_orig.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\entrecot-a-la-plancha-poco-hecho-receta.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\estofado.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\helado-de-vainilla.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\dinero-en-efectivo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\dinero.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\fregar-los-platos.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\help.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\iconoTPV.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\lasania.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\llamar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\logout.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\lupaIcono.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\menuCLientesOff.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\menuClientesOn.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\menuPedidosOff.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\menuPedidosOn.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\menuProductosOff.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\menuProductosOn.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\negocio-local.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\nuevoPedido.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\ojoOff.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\ojoOn.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\Paellavalenciana-4.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\pago-con-tarjetas-de-credito.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\perfil.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagenes\productos.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="imagenes\rioja-vega-crianza.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\salmon-horno-patatas-scaled.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\sopa-de-cebolla-receta.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imagenes\tarta-de-queso-de-la-vina.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="imagenes\tick.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
